# Server port
server.port=8081

# Origin server URL
proxy.origin.url=https://jsonplaceholder.typicode.com

# Cache TTL
proxy.cache.ttl.seconds=60

# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging
logging.level.com.sandhya.cachingproxy=DEBUG